### ISSUE TITLE
Error with Resnet Command line

### ISSUE THREAD

**Issue by reillydonovan** [gordicaleksa/pytorch-deepdream#8]
Hi, when I try to run the following command I am returned in error:
python3 deepdream.py --input cl_00001.png --img_width 1920 --pyramid_size 2 --model_name RESNET50 --pretrained_weights PLACES_365
Dreaming started!
Invalid layer names ['relu4_3'].
Available layers for model RESNET50 are ['layer1', 'layer2', 'layer3', 'layer4'].
Traceback (most recent call last):
  File "/home/reilly/Documents/Github/pytorch-deepdream/deepdream.py", line 236, in <module>
    dump_path = utils.save_and_maybe_display_image(config, img)
  File "/home/reilly/Documents/Github/pytorch-deepdream/utils/utils.py", line 87, in save_and_maybe_display_image
    assert isinstance(dump_img, np.ndarray), f'Expected numpy array got {type(dump_img)}.'
AssertionError: Expected numpy array got <class 'NoneType'>.

Again, any insight into how to resolve this would be greatly appreciated, thank you so much!

**Comment by reillydonovan** [comment]
python3 deepdream.py --input Clouds.mp4 --img_width 1920 --model_name RESNET50 --layers_to_use layer4 --pretrained_weight PLACES_365
